/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nlamei
 */
public class JDBC_form extends javax.swing.JFrame {

    /**
     * Creates new form JDBC_form
     */
    ArrayList<Person> myPList = new ArrayList();
    public JDBC_form() 
    {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTF = new javax.swing.JTextField();
        fnameTF = new javax.swing.JTextField();
        mnameTF = new javax.swing.JTextField();
        lnameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        idTF.setEnabled(false);
        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });
        getContentPane().add(idTF);
        idTF.setBounds(150, 20, 210, 30);

        fnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTFActionPerformed(evt);
            }
        });
        getContentPane().add(fnameTF);
        fnameTF.setBounds(150, 60, 210, 30);
        getContentPane().add(mnameTF);
        mnameTF.setBounds(150, 100, 210, 30);

        lnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTFActionPerformed(evt);
            }
        });
        getContentPane().add(lnameTF);
        lnameTF.setBounds(150, 140, 210, 30);
        getContentPane().add(emailTF);
        emailTF.setBounds(150, 180, 210, 30);
        getContentPane().add(phoneTF);
        phoneTF.setBounds(150, 220, 210, 30);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 14, 20);

        jLabel2.setText("First_Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 74, 20);

        jLabel3.setText("Middle_Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 89, 20);

        jLabel4.setText("Last_Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 140, 72, 20);

        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 180, 40, 20);

        jLabel6.setText("Phone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 220, 40, 20);

        newBtn.setText("New");
        newBtn.setActionCommand("newBtn");
        newBtn.setName(""); // NOI18N
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newBtn);
        newBtn.setBounds(100, 260, 86, 30);

        updateBtn.setText("Update");
        updateBtn.setActionCommand("updateBtn");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn);
        updateBtn.setBounds(220, 260, 90, 30);

        deleteBtn.setText("Delete");
        deleteBtn.setActionCommand("deleteBtn");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(340, 260, 90, 30);

        jButton4.setText("First");
        jButton4.setActionCommand("firstBtn");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 40, 100, 30);

        jButton5.setText("Previous");
        jButton5.setActionCommand("previousBtn");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(390, 80, 100, 30);

        jButton6.setText("Next");
        jButton6.setActionCommand("nextBtn");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(390, 120, 100, 30);

        jButton7.setText("Last");
        jButton7.setActionCommand("lastBtn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(390, 160, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTFActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_idTFActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
        Person newData = new Person(this.fnameTF.getText(),this.mnameTF.getText(),this.lnameTF.getText(),this.emailTF.getText(),this.phoneTF.getText());
       
        boolean insert =Con.Insertp(newData);
        JFrame f;
        if(insert)
        {
            this.myPList.add(newData);
            f = new JFrame();
            JOptionPane.showMessageDialog(f,"Successfully Inserted");
        }
       else
        {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,"Connection lost");            
        }
        
        
    }//GEN-LAST:event_newBtnActionPerformed

    private void fnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFrame f = new JFrame();
        myPList=Con.getall();
        
        try
        {
            this.idTF.setText(myPList.get(0).getId());
            this.fnameTF.setText(myPList.get(0).getFirstName());
            this.mnameTF.setText(myPList.get(0).getMiddleName());
            this.lnameTF.setText(myPList.get(0).getLastName());
            this.emailTF.setText(myPList.get(0).getEmail());
            this.phoneTF.setText(myPList.get(0).getPhone());    
        }
        catch(Exception e)
        {
            this.idTF.setText("");
            this.fnameTF.setText("");
            this.mnameTF.setText("");
            this.lnameTF.setText("");
            this.emailTF.setText("");
            this.phoneTF.setText("");
            JOptionPane.showMessageDialog(f,"Empty table");
          
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String id = this.idTF.getText();
        Person newData = new Person(this.fnameTF.getText(),this.mnameTF.getText(),this.lnameTF.getText(),this.emailTF.getText(),this.phoneTF.getText());
       
        boolean update = Con.Update(id,newData);
        JFrame f;
        if(update)
        {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,"Successfully Updated");
            myPList=Con.getall();

        }
        else
        {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,"Failed!");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        myPList=Con.getall();
        JFrame f;
        try
        {
            this.idTF.setText(myPList.get(myPList.size()-1).getId());
            this.fnameTF.setText(myPList.get(myPList.size()-1).getFirstName());
            this.mnameTF.setText(myPList.get(myPList.size()-1).getMiddleName());
            this.lnameTF.setText(myPList.get(myPList.size()-1).getLastName());
            this.emailTF.setText(myPList.get(myPList.size()-1).getEmail());
            this.phoneTF.setText(myPList.get(myPList.size()-1).getPhone());   
        }
        catch(Exception e)
        {   
            f = new JFrame();
            this.idTF.setText("");
            this.fnameTF.setText("");
            this.mnameTF.setText("");
            this.lnameTF.setText("");
            this.emailTF.setText("");
            this.phoneTF.setText("");
            JOptionPane.showMessageDialog(f,"Empty table");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String id = this.idTF.getText();
        boolean delete=Con.delete(id);
        
        JFrame f;
        
        if(delete)
        {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,"Successfully deleted");
            myPList=Con.getall();
        }
        else
        {
            f = new JFrame();
            JOptionPane.showMessageDialog(f,"Failed!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.myPList=Con.getall();
        String id = this.idTF.getText();
        Person p = new Person();
        int index=0;
        try
        {
            
        for(int i=0;i<this.myPList.size();i++)
        {
            if(id.equals(this.myPList.get(i).getId()))
            {
                index=i;
            }
        }
            p=this.myPList.get(index-1);
            this.idTF.setText(p.getId());
            this.fnameTF.setText(p.getFirstName());
            this.mnameTF.setText(p.getMiddleName());
            this.lnameTF.setText(p.getLastName());
            this.emailTF.setText(p.getEmail());
            this.phoneTF.setText(p.getPhone());    
        }
        catch(Exception e)
        {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"Failed!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        this.myPList=Con.getall();
        String id = this.idTF.getText();
        Person p = new Person();
        int index=0;
        try
        {
            
        for(int i=0;i<this.myPList.size();i++)
        {
            if(id.equals(this.myPList.get(i).getId()))
            {
                index=i;
            }
        }
            p=this.myPList.get(index+1);
            this.idTF.setText(p.getId());
            this.fnameTF.setText(p.getFirstName());
            this.mnameTF.setText(p.getMiddleName());
            this.lnameTF.setText(p.getLastName());
            this.emailTF.setText(p.getEmail());
            this.phoneTF.setText(p.getPhone());    
        }
        catch(Exception e)
        {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"Failed!");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBC_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBC_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBC_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBC_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Con con = new Con();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDBC_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lnameTF;
    private javax.swing.JTextField mnameTF;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
